name: Continuous Deployment
on:
  # pr on for testing
  pull_request:
    branches: [dev]
  # push: 
  #   branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: sam build
        working-directory: backend
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: backend

  e2e-test-backend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Run E2E Backend API Postman Tests
      run: |
        docker run -v $(pwd)/e2e/backend-api:/etc/newman -t postman/newman:latest run "VisitorCountAPI.postman_collection" --reporters="cli"

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: frontend/public

  e2e-test-frontend:
    needs: deploy-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./e2e/frontend/
        run: |
          npm i

      - name: Run tests
        working-directory: ./e2e/frontend/
        run: |
          npm run cy:run
        env:
          CI: true
