name: ci-backend
on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  backend-api-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        working-directory: ./backend
        run: |
          cd cloudresumechallenge/backend/tests
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: pytest
